### ISSUE TITLE
Make sfikas/medical-imaging-datasets accessible over web to help Community

### ISSUE THREAD

**Issue by Chetan11-dev** [sfikas/medical-imaging-datasets#16]
👋 Hi,
I came across your sfikas/medical-imaging-datasets repository and I must say, I am thoroughly impressed by the amount of work you have put in to gather these datasets for the community.

However, I noticed that it can be difficult to navigate through them. A website with a user-friendly web interface that showcases all of these datasets would be a great benefit to the community.

I would love to contribute by creating such a platform, similar to https://omkar.cloud/ (for free of course).
If you are interested, we can work together to make it easier for thousands of people to access the valuable datasets you have collected.

Let me know if you are interested in this collaboration.
Thanks,
Chetan Jain

**Comment by hollobit** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2023-02-10T01:34:04
          
          
            * 메일 제목 : 
[sfikas/medical-imaging-datasets] Make sfikas/medical-imaging-datasets accessible over web to help Community (Issue #16)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람의 메일함 용량이 가득 찼습니다.
받는 사람에게 메일함 정리를 요청하신 후 다시 발송해 보세요.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.
