### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by jaime-olivares** [sfikas/medical-imaging-datasets#17]
The following links are broken:

Pathology:
- Cancer Image Database (caIMAGE) https://emice.nci.nih.gov/caimage
- Aperio Images http://images.aperio.com/
- HAPS Histology Image Database http://hapshistology.wikifoundry.com/
- Locate Endogenus mouse sub-cellular organelles (END) database http://locate.imb.uq.edu.au/
- 2D HeLa dataset (HeLa) dataset https://ome.grc.nia.nih.gov/iicbu2008/hela/index.html
- DRIVE: Digital Retinal Images for Vessel Extraction http://www.isi.uu.nl/Research/Databases/DRIVE/ 

Databases:
- https://archive.ics.uci.edu/ml/datasets.php
- DermNet - Skin disease atlas (23 image classes and 23,000 images): http://www.dermnet.com/

**Comment by sfikas** [comment]
Many thanks!
